{% set name = "dwave-networkx" %}
{% set version = "0.8.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave_networkx-{{ version }}.tar.gz
  sha256: 01247c2ce63f9e6097497333968757ce097d2809b81fd9f5686652a56674e96c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dimod >=0.10.8,<0.13.0
    - networkx >=2.4,<3.0
    - python >=3.7

test:
  imports:
    - dwave_networkx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave_networkx
  summary: A NetworkX extension providing graphs and algorithms relevent to working with the D-Wave System
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
