{% set name = "dwave-networkx" %}
{% set version = "0.8.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dwave_networkx-{{ version }}.tar.gz
  sha256: b9d00e3f9dcc642572e676ffbca15b468204411724711cee606af285c30e6eca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.17.3
    - dimod >=0.10.8
    - networkx >=2.4
    - python >={{ python_min }}

test:
  imports:
    - dwave_networkx
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dwavesystems/dwave_networkx
  summary: A NetworkX extension providing graphs and algorithms relevent to working with the D-Wave System
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
